#!/bin/bash
#
# Export a commit from git to CVS.

if test -z "$1" || test -n "$2"; then
    echo Incorrect number of arguments
    exit 1
fi

export GIT_DIR=../git-emacs/.git
git cvsexportcommit -c -p -v $1
